docs: update meta data
BuildForSDG/Team-269-Frontend pull request #23
Opened 2020-05-21 11:45 UTC by onabright

## Description
I updated the app.properties file required for every project.

Fixes #22 

## How Has This Been Tested?
Used the instructions [provide here](https://github.com/BuildForSDG/.github/blob/master/app.properties)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

2020-05-21 14:41 UTC, MutegekiHenry approved these changes
Looks good to go

2020-05-22 06:50 UTC, MutegekiHenry commented on app.properties
> +team.mentors:
@onabright you could update team mentor details here

2020-05-22 06:51 UTC, MutegekiHenry requested changes
@onabright kindlly work on the feedback

2020-05-22 06:57 UTC, pearlonzo approved these changes

2020-05-22 09:27 UTC, luigimorel approved these changes

2020-05-22 09:54 UTC, pearlonzo approved these changes

2020-05-23 13:54 UTC, MutegekiHenry approved these changes

2020-05-23 13:54 UTC, merged